### ISSUE TITLE
Vagrant image contains incorrect apt keys

### ISSUE THREAD

**Issue by gmkey** [credativ/elephant-shed#10]
When running apt-get update on a freshly built vagrant image:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.credativ.com/public/postgresql stretch-test InRelease: The following signatures were invalid: EXPKEYSIG C86768840A59F867 aptly test repository (credativ) <aptly@credativ.de>
W: Failed to fetch https://packages.credativ.com/public/postgresql/dists/stretch-test/InRelease  The following signatures were invalid: EXPKEYSIG C86768840A59F867 aptly test repository (credativ) <aptly@credativ.de>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by gmkey** [comment]
curl https://packages.credativ.com/public/postgresql/aptly.key | sudo apt-key add -
solves the issue, but it took some reading to find the keys. maybe it's better to upload a new image to vagrant

**Comment by disco-stu** [comment]
Hey Gijs

Thanks for point out the apt-key error. The included key expired some time ago. We solved this problem by updating the key with our elephan-shed Debian packages. However, the Vagrant image wasn't updated after that.

We will update the Vagrant image within the next days.

Thanks

**Comment by df7cb** [comment]
Hi,
I just updated the Vagrant box to version 1.3.1: https://app.vagrantup.com/credativ/boxes/elephant-shed/versions/1.3.1
Thanks for spotting the problem!

We are also working on a new front-end design which should be ready over the next weeks. Stay tuned.

Christoph
