### ISSUE TITLE
Support for k8s (Docker)

### ISSUE THREAD

**Issue by foal** [credativ/elephant-shed#11]
Hey,

Do you also plan to support Docker/k8s installations?

Best,
Stanislav

**Comment by xxorde** [comment]
It would really great to:

* a) run all components on k8s
* b) automatically add and monitor all PostgreSQL instances running your k8s

Both things are on our bucket list but it's not clear when implementation will start.
If none of our customers request this features and sponsors parts of the development we most likely will not start in the next 6 month.

**Comment by df7cb** [comment]
The current Elephant Shed architecture is built on top of Debian's postgresql-common infrastructure which doesn't map to Docker/k8s, so this would really be a full rewrite.
