### ISSUE TITLE
how to join a new node in cluster already exists ?

### ISSUE THREAD

**Issue by changchichung** [credativ/elephant-shed#13]
I know it might be a simple/stupid question , but I can not find related documents.
let's said I create a new node , install elephant shed + postgresql , so there's only one node in main cluster now . so far so good .
then I create another new postgresql node , and I wanna join this node to the main cluster , how could I do that ?

**Comment by zesoup** [comment]
Hey @changchichung, 
If you are talking about the current master-branch with the multihost-overview - install Elephantshed on all nodes. Right now Elephantshed is designed around a dezentralised fat-client approach. Once this is done, the new clusters frontend should point you the right way.

The currently released and packaged version 1.3 had is no multihost support.

**Comment by df7cb** [comment]
The current 1.3 series doesn't have multi-node support yet, so closing this for now.
