### ISSUE TITLE
Grafana etc. not working on CentOS 7

### ISSUE THREAD

**Issue by dh9dat** [credativ/elephant-shed#14]
Hello,

I've just installed elephant shed on a fresh CentOS 7 system with PostgreSQL 12, but I can't see anything in Grafana: "Server" and "Cluster" are both showing "none" as the only entry, and all graphs are just showing "N/A".
But I can see my cluster 12/main on the start page, and there are also some values in cockpit etc., so, I'd suppose it's not a general problem.
Additionally, pgadmin is also not working, when I try to access it the browser just shows a http 500 error.
Any ideas what's wrong with my installation? Here's what I did:

1. yum install postgresql12-server
2. yum install https://packages.credativ.com/public/postgresql/yum/credativ-repo.rpm
3. yum install postgresql-common
4. pg_createcluster 12 main --start
5. yum install elephant-shed
6. vi /etc/group, added my user to elephant-shed group

Many thanks and best regards from Germany,

Harald

**Comment by koshkin-ccna** [comment]
The following PostgreSQL versions are currently supported:
* 11
* 10
* 9.6
* 9.5
* 9.4

**Comment by Strange-Panda** [comment]
> 
> 
> The following PostgreSQL versions are currently supported:
> 
>     * 11
> 
>     * 10
> 
>     * 9.6
> 
>     * 9.5
> 
>     * 9.4

Even with the recommend versions of PostgresSQL: I am able to reproduce this. 
I think this project is dead. Credativ is not responding. To bad. We even would pay for support.

**Comment by df7cb** [comment]
Hi, sorry for the embarrassingly late reply.

The grafana dashboard does work, but needs input from the prometheus-sql-exporter. If it doesn't know which server/cluster to show, check if `/run/postgresql/prometheus-sql-exporter.yml` knows about the clusters and databases (i.e. if the file is >> 100 bytes) and prometheus-sql-exporter.service is running. Also, waiting a bit after fixing anything, and then reloading the grafana page might help.
