### ISSUE TITLE
Installation on debian 10 with postgres 11

### ISSUE THREAD

**Issue by masterstrauch** [credativ/elephant-shed#19]
Hi,
I found a few problems with installing elephant-shed on debian 10 following https://elephant-shed.io/doc/chapter/installation.html

1. every 30s I get: " postgres@postgres ERROR:  pg_stat_statements must be loaded via shared_preload_libraries" in postgresql-Log

I think this comes from prometheus - adding "shared_preload_libraries = 'pg_stat_statements'" to postgres-conf fixes the issue

2. Activating archiving is not possible via Elephant-Shed Dashboard
the script " /usr/share/elephant-shed/pgbackrest-toggle-archiving" only sets archive_command, archive_mode is not activated, WAL-Parameters are also not set

I fixed it by adding the parameters myself - but I think that is not the intention of elephant-shed. So my complete "fix" is a conf-file within /etc/postgresql/11/main/conf.d/
listen_addresses='*'
wal_level = replica
fsync = on
synchronous_commit = on
wal_sync_method = fsync
archive_mode = on
archive_timeout = 900
shared_preload_libraries = 'pg_stat_statements'

**Comment by mbanck** [comment]
Thanks for your report, and sorry for the late reply.

It is true that those two parameters (and in particular the `archive_mode` one) are needed, but this is not explained in the rather ad-hoc manual installation instructions. The vagrant images do set them via Ansible so it should not be a problem there.

I will see about updating the documentation and including a paragraph about those parameters.

**Comment by mbanck** [comment]
I had another look at this and if you install `elephant-shed` first and some Postgres server package afterwards (as mentioned in the docs), Elephant-Shed sets up `shared_preload_library` and `archive_mode` appropriately via `/etc/postgresql-common/createcluster.d/elephant-shed.conf`.

So maybe the instances were created previously? This is of course supported, but then we expect the admin to set them up as needed, maybe this could be better documented though.

**Comment by masterstrauch** [comment]
Thanks for your message Michael.

I don't think, that the instance was installed before. My ansible-code for installation looks like this:
- name: INSTALL | install additional packages
  apt:
    name:
      - elephant-shed
      - postgresql-{{pg-version}}
      - python-psycopg2
     state:present
     install_recommends: no


But maybe it's a good idea to put the installation in two tasks to ensure that elephant-shed is installed fist. I try to test this next week with the current version of elephant-shed. 

Greetings Martin

**Comment by mbanck** [comment]
Yeah, we first install `elephant-shed` and then in a second step the PostgreSQL packages in our playbook, see 
https://github.com/credativ/elephant-shed/blob/rel1_3/vagrant/elephant-shed.yml#L52
and
https://github.com/credativ/elephant-shed/blob/rel1_3/vagrant/elephant-shed.yml#L63

**Comment by masterstrauch** [comment]
I've successfully tested the installation.  Thanks for your feedback.

As described in the other open issues, it would be really helpful if the docs are "up to date". I also would recommend to give a hint within changelog, if a update requires new repositories. Most admins (me too) run "apt update; apt upgrade" and if it don't work, they have a problem or need some time to figure out the problem. Fortunately a workmate was able to help me quickly. Afterwards I've seen in the vagrant-part at github what's happened.

Greetings Martin
