### ISSUE TITLE
pgadmin4-apache2 is dead

### ISSUE THREAD

**Issue by athlo** [credativ/elephant-shed#20]
and also 
`sudo apt install elephant-shed`
ends with error:
*elephant-shed : Depends: elephant-shed-pgadmin4 but it is not going to be installed*

repository: deb https://packages.credativ.com/public/postgresql/ bionic-stable main

**Comment by athlo** [comment]
sed -i 's/pgadmin4-apache2/pgadmin4-web/g' debian/control

**Comment by df7cb** [comment]
Yes we will have to modify that to cater for the different naming scheme of the pgadmin.org packages, thanks for pointing that out!

(And/or add support of OmniDB.)

**Comment by df7cb** [comment]
1.3.4 is out with OmniDB support.
