### ISSUE TITLE
Support for RPM-based Linux distributions

### ISSUE THREAD

**Issue by genadipost** [credativ/elephant-shed#3]
Hi,
This project looks great! Do you plan to support RPM based Linux distros (Fedora, Centos, Redhat)?

**Comment by disco-stu** [comment]
Hey,
Thanks. RHEL / CentOS (at least 7) is definitely on our roadmap. But, to be honest: don't expect it within the next weeks. Beside porting the deb packages to rpm another lavish part is the packaging of all required 3rd party apps like Grafana, Prometheus, SQL-Export and so on.

**Comment by genadipost** [comment]
Thank you for the info.

**Comment by ChristophBerg** [comment]
RedHat/CentOS 7 is now supported. (ba3780be0256)
