### ISSUE TITLE
question about getting elephant-shed to work with a customized PostgreSQL

### ISSUE THREAD

**Issue by nawazahmed1** [credativ/elephant-shed#7]
Hi Support Team,

I have  configured a customized PostgreSQL (Fujitsu Enterprise Postgres) in which all the binaries and libraries are in a non-default location. I wanted to know what files do i need to edit in order to update all the locations to have a completely working elephant shed. I have currently installed it on a host, I can only see the grafana-server and prometheus processes active while the rest of the services (systemd unit files) are either not started or not configured.

I can login to the portal but i could not see the clusters information and I take it that it is due to the fact that postgresql binaries are in a non-default location. I could navigate to grafana portal but all the meters and graphs are empty with not data in it. 

Please help me to configure it so i can have a fully working setup.

Regards,
Nawaz Ahmed

**Comment by ChristophBerg** [comment]
Hi,
Elephant Shed is built around postgresql-common, so most things will Just Work if postgresql-common supports them, i.e. `pg_lsclusters` needs to list the clusters.
The most important step is to make the cluster config visible by putting it into the /etc/postgresql/$version/$cluster structure, either physically, or by creating symlinks, e.g. /etc/postgresql/11/fujitsu -> /var/lib/pgfujitsu/data. That step should enable the listing of clusters in the ES portal.
Some functions also scan for the list of available PostgreSQL versions by looking for /usr/lib/postgresql/*/bin/psql (or initdb). Symlinks should help there as well.

I'm pondering supporting more file locations by default in postgresql-common. Does your PG installation have locations that are standardized in such a way that they could be autodiscovered in a sane way?

**Comment by nawazahmed1** [comment]
Hi Christoph, 

Thank you for the response.

The Fujitsu postgres binaries are installed in /opt/fsepv[%n%n]server64/bin and the cluster's data directory can be anywhere.

I see that the tool has been develolped to auto-discover on an Ubuntu and Debian flavor of Linux but I am running a Fujitsu postgres on a CentOS.

In order to get it to work, I followed the below steps based on your response and it did not work. I think I may have goofed-up, could you please correct it.


fsep      4556     1  1 10:45 pts/0    00:00:00 /opt/fsepv95server64/bin/postgres -D /database/data
fsep      4584  4556  0 10:45 ?        00:00:00 postgres: logger process
fsep      4596  4556  0 10:45 ?        00:00:00 postgres: checkpointer process
fsep      4597  4556  0 10:45 ?        00:00:00 postgres: writer process
fsep      4598  4556  0 10:45 ?        00:00:00 postgres: wal writer process
fsep      4599  4556  0 10:45 ?        00:00:00 postgres: autovacuum launcher process
fsep      4600  4556  0 10:45 ?        00:00:00 postgres: stats collector process

[root@CentOS72 postgresql]# mkdir -p /etc/postgresql/95
[root@CentOS72 postgresql]# ln -s /database/data /etc/postgresql/95/fsep95
[root@CentOS72 postgresql]# cd /etc/postgresql/95
[root@CentOS72 95]# ls -ltr
total 0
lrwxrwxrwx. 1 root root 14 Feb 26 10:15 fsep95 -> /database/data

**Comment by ChristophBerg** [comment]
Could you try the following?
```
mkdir -p /usr/pgsql-9.5
ln -s /opt/fsepv95server64/bin /usr/pgsql-9.5/bin
mkdir -p /etc/postgresql/9.5
ln -s /database/data /etc/postgresql/9.5/fsep95
```
Yesterday I missed the fact that setting up a bin directory is required for the autodetection to work. On CentOS, it is looking for /usr/pgsql-*/bin/psql.

**Comment by ChristophBerg** [comment]
I'll transfer this to the postgresql-common TODO list.

**Comment by nawazahmed1** [comment]
The last set of troubleshooting steps as below did not fix the issue but I am happy for you to close the issue and add it to the TODO list. 

mkdir -p /usr/pgsql-9.5
ln -s /opt/fsepv95server64/bin /usr/pgsql-9.5/bin
mkdir -p /etc/postgresql/9.5
ln -s /database/data /etc/postgresql/9.5/fsep95

The Fujitsu's Enterprise Postgres always has its executables and library files as below 

/opt/fsepv[NN]server[nn]/bin
/opt/fsepv[NN]server[nn]/lib
/opt/fsepv[NN]server[nn]/include
/opt/fsepv[NN]server[nn]/share

where 
NN : 95 or 96 or 10 or 11 (depends on the version of the base PostgreSQL)
nn: 64 (offcourse 32 word size is no longer supported)

Cheers,
Nawaz
