### ISSUE TITLE
Consider to use a manger configurator to manage external or multiple cluster

### ISSUE THREAD

**Issue by omm1979** [credativ/elephant-shed#8]
Hi, I think this tools are awsome, and i'm interested in elephant-shed, but like you said in the note of 4.1.2. Cluster Administration section, "Note: Future versions of The Elephant Shed will include cluster management in the portal." This means I can't manage clusters out of the main Elephant-Shed enviroment (PostgreSQL, pgAdmin4, postgresql-common, pgBadger, pgBackRest, Grafana, Prometheus, Cockpit, Shell In A Box),  I can just manage postgresql instance in the same cluster where all of Elephant-Shed tools are, isn't it?, because I want to connect all of them (Elephant-Shed Tools) to manage another postgresql cluster, like configurate postgresql connection to manage different postgresql cluster o instances and control them, like pgAdmin do it, but I suppose it would be an enterprise edition o Non-free edition, I said all of above because having (every and each of them -tools-) in one server, for security and performance it's a bit dangerous, i would like to receive notices and news from you to follow the advance and in one moment implement in my infrastructure, thanks a lot and regards.

**Comment by ChristophBerg** [comment]
Hi,
"cluster" in this context refers to PostgreSQL instances, i.e. running database processes. It doesn't mean "HA cluster of several machines". The naming is agreeably confusing. So what Elephant Shed currently does, is to let you manage a set of PostgreSQL clusters (instances) running on the local machine.

We are working on making remote hosts accessible and integrated into that framework. You can check out the progress in the `rework_frontend` branch. It uses https://github.com/credativ/pgapi.

It will still be fully Open Source, there will be no enterprise or whatever edition.

Hope that explains it.
